[versions]
agp = "8.1.4"
dagger = "2.48.1"
kotlin = "1.9.20"
kotest = "5.8.0"
ktlint = "1.0.1"
lint = "31.1.4"
landscapist = "2.2.12"
firebase = "1.10.4"

[libraries]
android-core = "androidx.core:core-ktx:1.12.0"
android-lifecycle = "androidx.lifecycle:lifecycle-runtime-ktx:2.6.2"
android-compose-activity = "androidx.activity:activity-compose:1.8.1"
android-compose-navigation = "androidx.navigation:navigation-compose:2.7.5"
android-google-oss-licenses = "com.google.android.gms:play-services-oss-licenses:17.0.1"
coil = "com.github.skydoves:landscapist-coil:2.2.12"
placeholder = "com.github.skydoves:landscapist-placeholder:2.2.12"
accompanist-navigation-material = "com.google.accompanist:accompanist-navigation-material:0.32.0"
coroutines = "org.jetbrains.kotlinx:kotlinx-coroutines-core:1.7.3"
compose-bom = "androidx.compose:compose-bom:2023.10.01"
compose-ui-ui = { group = "androidx.compose.ui", name = "ui" }
compose-ui-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
compose-material-icons = { group = "androidx.compose.material", name = "material-icons-extended" }
compose-material3 = { group = "androidx.compose.material3", name = "material3" }
compose-material3-window-size = { group = "androidx.compose.material3", name = "material3-window-size-class" }
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "dagger" }
hilt-android-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "dagger" }
hilt-compiler = "androidx.hilt:hilt-compiler:1.1.0"
hilt-navigation = "androidx.hilt:hilt-navigation-compose:1.1.0"
hilt-work = "androidx.hilt:hilt-work:1.1.0"
firebase-bom = "com.google.firebase:firebase-bom:32.6.0"
firebase-analytics = { module = "com.google.firebase:firebase-analytics-ktx" }
firebase-crashlytics = { module = "com.google.firebase:firebase-crashlytics-ktx" }
firebase-storage = { module = "com.google.firebase:firebase-storage-ktx" }
firebase-firestore = { module = "dev.gitlive:firebase-firestore", version.ref = "firebase" }
firebaseui-auth = "com.firebaseui:firebase-ui-auth:8.0.2"
play-services-auth = "com.google.android.gms:play-services-auth:20.7.0"
leakcanary = "com.squareup.leakcanary:leakcanary-android:2.12"
lint-api = { group = "com.android.tools.lint", name = "lint-api", version.ref = "lint" }
ktlint-cli = { group = "com.pinterest.ktlint", name = "ktlint-cli", version.ref = "ktlint" }
ktlint-ruleset = { group = "com.pinterest.ktlint", name = "ktlint-cli-ruleset-core", version.ref = "ktlint" }
material = "com.google.android.material:material:1.10.0"
workmanager = "androidx.work:work-runtime-ktx:2.8.1"

test-guava = "com.google.guava:guava:32.1.3-jre"
test-mockk = "io.mockk:mockk:1.13.8"
test-lint = { group = "com.android.tools.lint", name = "lint", version.ref = "lint" }
test-lint-tests = { group = "com.android.tools.lint", name = "lint-tests", version.ref = "lint" }
test-junit-launcher = "org.junit.platform:junit-platform-launcher:1.10.1"
test-kotest-engine = { module = "io.kotest:kotest-framework-engine", version.ref = "kotest" }
test-kotest-runner = { module = "io.kotest:kotest-runner-junit5", version.ref = "kotest" }
test-kotest-datatest = { module = "io.kotest:kotest-framework-datatest", version.ref = "kotest" }
test-kotlin = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
test-ktlint = { group = "com.pinterest.ktlint", name = "ktlint-test", version.ref = "ktlint" }
test-slf4j = "org.slf4j:slf4j-simple:2.0.9"

[bundles]
lint-test = ["test-lint", "test-lint-tests"]

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
google-services = { id = "com.google.gms.google-services", version.strictly = "4.4.0" }
hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "dagger" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-ksp = { id = "com.google.devtools.ksp", version.strictly = "1.9.20-1.0.14" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotest = { id = "io.kotest.multiplatform", version.ref = "kotest" }
oss-licenses = { id = "com.google.android.gms.oss-licenses-plugin" }
firebase-appdistribution = { id = "com.google.firebase.appdistribution", version.strictly = "4.0.1" }
firebase-crashlytics = { id = "com.google.firebase.crashlytics", version.strictly = "2.9.9" }
