name: Lint
on:
  pull_request:
  push:
    branches:
      - dev
jobs:
  lint-debug:
    runs-on: ubuntu-latest
    container: gradle:8.4.0-jdk17
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/gradle-cache
      - uses: android-actions/setup-android@v3.2.0
      - uses: ./.github/actions/firebase-google-service
        with:
          secret: ${{ secrets.FIREBASE_GOOGLE_SERVICE }}
      - run: ./gradlew lintDebug
      - uses: github/codeql-action/upload-sarif@v2
        if: ${{ always() }}
        with:
          sarif_file: app/build/reports/lint-results-debug.sarif
          category: lint
  ktlint-check:
    runs-on: ubuntu-latest
    container: gradle:8.4.0-jdk17
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/gradle-cache
      - run: ./gradlew ktlintCheck
